package router

import (
	"net/http"

	// docs is generated by Swag CLI, you have to import it.
	"github.com/gin-contrib/pprof"
	"github.com/gin-gonic/gin"
	_ "github.com/yufenghui/apiserver/docs"
	"github.com/yufenghui/apiserver/handler/sd"
	"github.com/yufenghui/apiserver/handler/user"
	"github.com/yufenghui/apiserver/router/middleware"

	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// load middlewares, routes, handlers
func Load(g *gin.Engine, mw ...gin.HandlerFunc) *gin.Engine {

	// Middlewares
	g.Use(gin.Recovery())
	g.Use(middleware.NoCache)
	g.Use(middleware.Options)
	g.Use(middleware.Secure)
	g.Use(mw...)

	g.NoRoute(func(c *gin.Context) {
		c.String(http.StatusNotFound, "Not found!")
	})

	// swagger api docs
	g.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// pprof router
	pprof.Register(g)

	// api for authentication functionalities
	g.POST("/login", user.Login)

	u := g.Group("/v1/user")
	u.Use(middleware.AuthMiddleware())
	{
		// 创建用户
		u.POST("", user.Create)
		// 删除用户
		u.DELETE("/:id", user.Delete)
		// 更新用户
		u.PUT("/:id", user.Update)
		// 用户列表
		u.GET("", user.List)
		// 获取指定用户的详细信息
		u.GET("/:username", user.Get)
	}

	svcd := g.Group("/sd")
	{
		svcd.GET("/health", sd.HealthCheck)
	}

	return g
}
